name: Balraj test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  Greeting: My jobs
  url: https://www.youtube.com/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $SABHARWAL_SECURE
        env:
         sabharwal_SECURE: ${{ secret.SABHARWAL_SECRETS }}
  
  display:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    environment:
      name: display

    steps:
      - name: Print the value 
        run: echo balraj sabharwal
        
  production:
    runs-on: ubuntu-latest
 
    environment:
      name: display

    steps:
      - name: Print the value 
        run: echo balraj 

